### ISSUE TITLE
Define working colorlight i9 -- only the onboard led

### ISSUE THREAD

**Issue by sporniket** [sporniket/amaranth_sandbox#4]
There are several pull request for this board that I now own, none is integrated, yet.

The goal is to have a working blinky. The scripts will not be organized.

See [reference of pins](https://github.com/wuxx/Colorlight-FPGA-Projects/blob/master/colorlight_i9_v7.2.md)

### TODO 

* [ ] Board class, with only user LED (L2)
* [ ] Blinky module (1 second cycle, 50% duty cycle)
* [ ] Bitstream generation that works on the board
